# name: Linter and Unit Testing

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
# jobs:
#   lint-and-test:
#     runs-on: ubuntu-latest
#     env:
#       DEV_API_URL: "https://rickandmortyapi.com/graphql"
#       PRODUCTION_API_URL: ''
#       IS_STORYBOOK: false
#       SENTRY_DSN: ''
#       SEGMENT_DSN: ''
#     steps:
#       - name: Checkout project
#         uses: actions/checkout@v1

#       - name: Specify node version
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12

#       - name: Install node_modules
#         run: |
#           yarn install --frozen-lockfile
#       - name: Run Prettier and Eslint
#         run: |
#           yarn eslint-check-all && yarn prettier-check-all
#       - name: Test
#         timeout-minutes: 10
#         run: |
#           yarn jest --verbose
